spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000

# shiro配置
shiro:
  session:
    sessionKeyPrefix: SESSION:SHIRO_SESSION_
    sessionExpiredTime: 600
  cache:
    cacheKey: SHIRO_CACHE